CREATE TABLE PROFESOR(
    DNI_PROFESOR VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(41) NOT NULL,
    AP1 VARCHAR(35) NOT NULL,
    AP2 VARCHAR(35) NULL,
    DIRECCION VARCHAR(35) NOT NULL,
    CUENTA VARCHAR(5) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    CONSTRAINT PK_PROFESOR PRIMARY KEY(DNI_PROFESOR),
    CONSTRAINT FK_PROFESOR FOREIGN KEY(DNI_PROFESOR) REFERENCES DATOSPERSONALES(DNI)
);

CREATE TABLE CICLOFORM(
    CODCICLO NUMBER(3) NOT NULL,
    NOMBRE VARCHAR(41) NOT NULL,
    TIPO VARCHAR(35) NOT NULL,
    CONSTRAINT PK_CICLOFORM PRIMARY KEY(CODCICLO)
);

CREATE TABLE ASIGNATURA(
    CODASIG NUMBER(3) NOT NULL,
    NOMBRE VARCHAR(41) NOT NULL,
    NUMHORAS NUMBER(3) NOT NULL,
    DNI_PROFESOR VARCHAR(9) NOT NULL,
    CODCICLO NUMBER(3) NOT NULL,
    CONSTRAINT PK_ASIGNATURA PRIMARY KEY(CODASIG),
    CONSTRAINT FK_PROFESOR FOREIGN KEY(DNI_PROFESOR) REFERENCES PROFESOR(DNI_PROFESOR),
    CONSTRAINT FK_CICLOFORM FOREIGN KEY(CODCICLO) REFERENCES CICLOFORM(CODCICLO)
);

CREATE TABLE IDIOMA(
    CODIDIOMA NUMBER(3) NOT NULL,
    DESCRIPCION VARCHAR(50) NOT NULL,
    CONSTRAINT PK_IDIOMA PRIMARY KEY(CODIDIOMA)
);

CREATE TABLE ALUMNO(
    DNI_ALUMNO VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(41) NOT NULL,
    AP1 VARCHAR(35) NOT NULL,
    AP2 VARCHAR(35) NULL,
    DIRECCION VARCHAR(35) NOT NULL,
    EMAIL VARCHAR(36) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    CODIDIOMA NUMBER(3) NULL,
    CONSTRAINT PK_ALUMNO PRIMARY KEY(DNI_ALUMNO),
    CONSTRAINT FK_IDIOMA FOREIGN KEY(CODIDIOMA) REFERENCES IDIOMA(CODIDIOMA),
    CONSTRAINT FK_ALUMNO FOREIGN KEY(DNI_ALUMNO) REFERENCES DATOSPERSONALES(DNI)
);

CREATE TABLE MATRICULA(
    CODASIG NUMBER(3) NOT NULL,
    DNI_ALUMNO VARCHAR(9) NOT NULL,
    CONSTRAINT PK_MATRICULA PRIMARY KEY(DNI_ALUMNO, CODASIG),
    CONSTRAINT FK_ASIGNATURA FOREIGN KEY(CODASIG) REFERENCES ASIGNATURA(CODASIG),
    CONSTRAINT FK_ALUMNO FOREIGN KEY (DNI_ALUMNO) REFERENCES ALUMNO(DNI_ALUMNO)
);

CREATE TABLE IDIOMASPROF(
    CODIDIOMA NUMBER(3) NOT NULL,
    DNI_PROFESOR VARCHAR(9) NOT NULL,
    CONSTRAINT PK_IDIOMASPROF PRIMARY KEY(CODIDIOMA, DNI_PROFESOR),
    CONSTRAINT FK_IDIOMA FOREIGN KEY(CODIDIOMA) REFERENCES IDIOMA(CODIDIOMA),
    CONSTRAINT FK_PROFESOR FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESOR(DNI_PROFESOR)
);

CREATE TABLE DATOSPERSONALES(
    DNI VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO1 VARCHAR(20) NOT NULL,
    APELLIDO2 VARCHAR(20),
    DIRECCION VARCHAR(30) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    TIPO VARCHAR(2) NOT NULL
);

ALTER TABLE PROFESOR DROP (NOMBRE);
ALTER TABLE PROFESOR DROP (AP1);
ALTER TABLE PROFESOR DROP (AP2);
ALTER TABLE PROFESOR DROP (DIRECCION);
ALTER TABLE PROFESOR DROP (TELEFONO);

ALTER TABLE ALUMNO DROP (NOMBRE);
ALTER TABLE ALUMNO DROP (AP1);
ALTER TABLE ALUMNO DROP (AP2);
ALTER TABLE ALUMNO DROP (DIRECCION);
ALTER TABLE ALUMNO DROP (TELEFONO);

ALTER TABLE DATOSPERSONALES ADD CONSTRAINT PK_DATOSPERSONALES PRIMARY KEY(DNI);

ALTER TABLE PROFESOR ADD CONSTRAINT FK_DATOSPERSONALES FOREIGN KEY(DNI_PROFESOR) REFERENCES DATOSPERSONALES(DNI) ON DELETE CASCADE;
ALTER TABLE ALUMNO ADD CONSTRAINT FK_ALUMNO FOREIGN KEY(DNI_ALUMNO) REFERENCES DATOSPERSONALES(DNI) ON DELETE CASCADE;

ALTER TABLE DATOSPERSONALES ADD CONSTRAINT CHECK(TIPO IN('PROFESOR','ALUMNO'));

